### ISSUE TITLE
Change phase 2 light options from Full/Half/Empty to Full,3/4,1/2,1/4,Empty

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/Leaf-Glucose-Simulation#10]
Request by Eliane:
For phase 2, can we have Full, 3/4, 1/2, 1/4 and 0 light? Full would be 4 photons instead of 2. When there is 3/4 light, it makes 3 glucose, 1/4 makes 1 glucose. When there is 1/4 light, the plant sends the newly-made glucose to the mitochondria, along with a glucose from storage. The plant dies when at least one of the energy needs is not met, so if the light is on 1/4 from the beginning, the plant will die at the end of the first day (same as if the light was off).

**Comment by hirokiterashima** [comment]
@KWiley05 @annarafferty Eliane

Just to clarify, if there's 2 glucose in storage at the beginning of the day, and the light is set to 1/4, the chloroplast produces 1 glucose and 1 glucose will be retrieved from storage to make enough energy to meet the day's needs. At the end of the day, 1 glucose is left in storage. Does this sound correct?

**Comment by annarafferty** [comment]
This sounds correct to me.

**Comment by elianewiese** [comment]
Yes.

**Comment by hirokiterashima** [comment]
Hi @KWiley05 @annarafferty @elianewiese I implemented the 5 different light options. Can you test it out and let me know if it works ok?
https://wise-community.github.io/Leaf-Glucose-Simulation/dist/index.html?lightMode=5

**Comment by elianewiese** [comment]
The glucose animations look good! One issue is that the light bulb doesn't turn off when the light is at 0. there are no photons, but the bulb is still yellow. Can we also have the different background colors for different amounts of light?

**Comment by hirokiterashima** [comment]
Changing the background color based on amount of light was implemented in #12. I also fixed the code so the light turns off when number of photons = 0. 

This resolves all issues related to this ticket, closing issue.
