### ISSUE TITLE
Update band colors on graph based on level of light

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/Leaf-Glucose-Simulation#12]
Request by Eliane

With different levels of light, it would be nice to show different colors on the graph. Sample colors attached.

[Sample Graph Background Colors.pptx](https://github.com/WISE-Community/Leaf-Glucose-Simulation/files/1311544/Sample.Graph.Background.Colors.pptx)

**Comment by hirokiterashima** [comment]
Additional request by Korah:
Also can the plant background change in accordance with the light level change?

We should also update the background image in the day number corner as well.

**Comment by elianewiese** [comment]
Thanks Hiroki!

**Comment by hirokiterashima** [comment]
@elianewiese the sample graph background colors ppt only contains 4 colors, but we actually need 5 for the model: 100, 75, 50, 25, off. What's the fifth color, and how should the colors map to the different light strengths?

**Comment by elianewiese** [comment]
[
[5 Sample Graph Background Colors.pptx](https://github.com/WISE-Community/Leaf-Glucose-Simulation/files/1369716/5.Sample.Graph.Background.Colors.pptx)
](url)

**Comment by hirokiterashima** [comment]
@KWiley05 @elianewiese 
This has been implemented. You can see the new band colors here: https://wise-community.github.io/Leaf-Glucose-Simulation/dist/index.html?numLightOptions=5

**Comment by elianewiese** [comment]
Graph background is too dark when the plant is in the dark. Can we use this color instead?
![light_off_graph_background](https://user-images.githubusercontent.com/19541214/31558863-cc2a9de4-b00b-11e7-8580-66444dcf01d5.png)
