### ISSUE TITLE
Improve glucose movement from Chloroplast to storage

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/Leaf-Glucose-Simulation#2]
Feedback from Geoff:
The movement of the glucose looks a little weird because when they move down, they start to overlap, but then when they get to their destination they snap apart.

Instead:
Calculate the end positions of each glucose and make them move there so it looks like one smooth animation.

**Comment by elianewiese** [comment]
sounds fancy.

**Comment by hirokiterashima** [comment]
This fancy improvement was added in this commit: 919543ef54376740ba27dd0864cd648e5b4550d0
