### ISSUE TITLE
Show 4 Photons for Light On in Phase 1 Model

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/Leaf-Glucose-Simulation#9]
Request by Eliane

For continuity between phase 1 and phase 2 of the model, show that when the light is on, 4 photons are sent to plant leaf and chloroplast, and 4 glucose is created in the chloroplast.

**Comment by geoffreykwan** [comment]
Completed https://github.com/WISE-Community/Leaf-Glucose-Simulation/commit/957069c26b67991a2cd46807b9778af72005e6f3
